services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: meetinghub
      POSTGRES_PASSWORD: meetinghub
      POSTGRES_DB: meetinghub
    ports:
      - "5434:5432"
    volumes:
      - meetinghub_pg:/var/lib/postgresql/data

volumes:
  meetinghub_pg:
